server:
  port: 8084

spring:
  application:
    name: transaction_service_api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    shard1:
      jdbc-url: jdbc:postgresql://localhost:5432/transaction_service_api_shard1
      username: postgres
      password: root
    shard2:
      jdbc-url: jdbc:postgresql://localhost:5432/transaction_service_api_shard2
      username: postgres
      password: root
  flyway:
    enabled: false
    locations: classpath:db/migration
    user: ${spring.datasource.shard1.username}
    password: ${spring.datasource.shard1.password}

logging:
  level:
    org.springframework.web: INFO

